version: '2.4'   # '3.9' or greater also works
services:
    archivebox:
        image: ${DOCKER_IMAGE:-archivebox/archivebox:master}
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            - ALLOWED_HOSTS=*                   # add any config options you want as env vars
            - MEDIA_MAX_SIZE=3000m
        volumes:
            - /DATA_DIR/:/data
            # - ./archivebox:/app/archivebox    # for developers working on archivebox
