version: '3.6'
services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:2.0.0-latest
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ./monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "820:5000"
    restart: unless-stopped
    networks:
      checkmk:

networks:
    checkmk:
